"""Monthly client PDF reports — WeasyPrint, Supabase Storage `reports` bucket, Resend."""

from __future__ import annotations

import base64
import logging
import os
from datetime import datetime
from io import BytesIO
from typing import Any
from zoneinfo import ZoneInfo

import httpx

from config import BASE_URL, RESEND_API_KEY, RESEND_FROM_EMAIL

logger = logging.getLogger(__name__)

SUPABASE_URL = os.environ.get("SUPABASE_URL", "").strip().rstrip("/")
SUPABASE_SERVICE_ROLE_KEY = os.environ.get("SUPABASE_SERVICE_ROLE_KEY", "").strip()


def _sb_headers() -> dict[str, str]:
    return {
        "apikey": SUPABASE_SERVICE_ROLE_KEY,
        "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
        "Content-Type": "application/json",
    }


def _escape(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def _findings_list(findings: Any) -> list[dict[str, Any]]:
    if findings is None:
        return []
    if isinstance(findings, list):
        return [x for x in findings if isinstance(x, dict)]
    if isinstance(findings, dict):
        inner = findings.get("findings") or findings.get("items")
        if isinstance(inner, list):
            return [x for x in inner if isinstance(x, dict)]
    return []


def build_monthly_html(
    *,
    company_name: str,
    domain: str,
    month_label: str,
    scan: dict[str, Any] | None,
) -> str:
    score = scan.get("hawk_score") if scan else None
    grade = scan.get("grade") if scan else None
    findings = _findings_list(scan.get("findings") if scan else None)
    critical = [f for f in findings if f.get("severity") == "critical"]
    warning = [f for f in findings if f.get("severity") == "warning"]

    parts = [
        "<!DOCTYPE html><html><head><meta charset=\"utf-8\"/>",
        """<style>
body { font-family: system-ui, sans-serif; font-size: 12px; color: #111; max-width: 800px; margin: 0 auto; padding: 24px; }
h1 { font-size: 20px; }
h2 { font-size: 15px; margin-top: 20px; border-bottom: 1px solid #ddd; }
.meta { color: #555; margin-bottom: 16px; }
table { width: 100%; border-collapse: collapse; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #eee; }
.footer { margin-top: 24px; font-size: 11px; color: #888; }
</style></head><body>",
        f"<h1>HAWK — Monthly security summary</h1>",
        f'<p class="meta">{_escape(month_label)} · {_escape(company_name)} · {_escape(domain)}</p>',
    ]
    if scan:
        parts.append(f"<p><strong>Latest scan score:</strong> {score if score is not None else '—'} / 100 · Grade {_escape(str(grade or '—'))}</p>")
        parts.append(f"<p>Critical findings: {len(critical)} · Warnings: {len(warning)}</p>")
        if findings:
            parts.append("<h2>Top findings</h2><table><thead><tr><th>Severity</th><th>Title</th></tr></thead><tbody>")
            for f in findings[:25]:
                sev = _escape(str(f.get("severity", "")))
                title = _escape(str(f.get("title", "")))
                parts.append(f"<tr><td>{sev}</td><td>{title}</td></tr>")
            parts.append("</tbody></table>")
    else:
        parts.append("<p>No completed prospect scan on file for this period — contact your HAWK rep.</p>")

    parts.append(f'<p class="footer">Generated by HAWK — {BASE_URL}</p></body></html>')
    return "\n".join(parts)


def html_to_pdf_bytes(html: str) -> bytes | None:
    try:
        from weasyprint import HTML
    except ImportError:
        logger.warning("weasyprint not installed — skip PDF")
        return None
    buf = BytesIO()
    HTML(string=html).write_pdf(buf)
    return buf.getvalue()


def upload_report_pdf(path: str, data: bytes) -> bool:
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        return False
    url = f"{SUPABASE_URL}/storage/v1/object/reports/{path}"
    try:
        r = httpx.post(
            url,
            headers={
                "apikey": SUPABASE_SERVICE_ROLE_KEY,
                "Authorization": f"Bearer {SUPABASE_SERVICE_ROLE_KEY}",
                "Content-Type": "application/pdf",
                "x-upsert": "true",
            },
            content=data,
            timeout=120.0,
        )
        if r.status_code not in (200, 201):
            logger.error("storage upload %s: %s %s", path, r.status_code, r.text[:500])
            return False
        return True
    except Exception as e:
        logger.exception("upload_report_pdf: %s", e)
        return False


def send_monthly_email(*, to_email: str, company_name: str, month_label: str, pdf_b64: str) -> dict[str, Any]:
    if not RESEND_API_KEY:
        return {"skipped": True, "reason": "RESEND_API_KEY not set"}
    body = {
        "from": RESEND_FROM_EMAIL,
        "to": [to_email],
        "subject": f"HAWK monthly report — {company_name} ({month_label})",
        "html": f"<p>Your monthly HAWK security summary for <strong>{_escape(company_name)}</strong> is attached.</p>",
        "attachments": [{"filename": f"hawk-monthly-{month_label}.pdf", "content": pdf_b64}],
    }
    r = httpx.post(
        "https://api.resend.com/emails",
        headers={"Authorization": f"Bearer {RESEND_API_KEY}", "Content-Type": "application/json"},
        json=body,
        timeout=60.0,
    )
    r.raise_for_status()
    return r.json()


def _report_month_year_mst() -> tuple[str, str]:
    """Previous calendar month in America/Denver, e.g. ('2026-02', 'February 2026')."""
    now = datetime.now(ZoneInfo("America/Denver"))
    y, m = now.year, now.month
    if m == 1:
        y, m = y - 1, 12
    else:
        m -= 1
    key = f"{y:04d}-{m:02d}"
    label = datetime(y, m, 1, tzinfo=ZoneInfo("America/Denver")).strftime("%B %Y")
    return key, label


def run_monthly_client_reports() -> dict[str, Any]:
    """
    For each active client with a portal email, latest scan -> PDF -> storage -> Resend.
    Idempotent via crm_monthly_report_log unique (client_id, month_year).
    """
    if not SUPABASE_URL or not SUPABASE_SERVICE_ROLE_KEY:
        return {"ok": False, "error": "supabase not configured", "sent": 0}

    month_year, month_label = _report_month_year_mst()

    r = httpx.get(
        f"{SUPABASE_URL}/rest/v1/clients",
        headers=_sb_headers(),
        params={"select": "id,company_name,domain,prospect_id,status", "status": "eq.active", "limit": "500"},
        timeout=45.0,
    )
    r.raise_for_status()
    clients = r.json() or []

    sent = 0
    skipped = 0
    errors: list[str] = []

    for c in clients:
        cid = c.get("id")
        prospect_id = c.get("prospect_id")
        if not cid:
            continue

        prev = httpx.get(
            f"{SUPABASE_URL}/rest/v1/crm_monthly_report_log",
            headers=_sb_headers(),
            params={"client_id": f"eq.{cid}", "month_year": f"eq.{month_year}", "select": "id,status", "limit": "1"},
            timeout=15.0,
        )
        prev.raise_for_status()
        prev_rows = prev.json() or []
        if prev_rows:
            st = prev_rows[0].get("status")
            if st == "sent":
                skipped += 1
                continue
            if st == "failed":
                pid = prev_rows[0].get("id")
                if pid:
                    httpx.delete(
                        f"{SUPABASE_URL}/rest/v1/crm_monthly_report_log",
                        headers=_sb_headers(),
                        params={"id": f"eq.{pid}"},
                        timeout=15.0,
                    )

        pr = httpx.get(
            f"{SUPABASE_URL}/rest/v1/client_portal_profiles",
            headers=_sb_headers(),
            params={"client_id": f"eq.{cid}", "select": "email", "limit": "1"},
            timeout=15.0,
        )
        pr.raise_for_status()
        profs = pr.json() or []
        to_email = profs[0].get("email") if profs else None
        if not to_email:
            skipped += 1
            continue

        scan: dict[str, Any] | None = None
        if prospect_id:
            sr = httpx.get(
                f"{SUPABASE_URL}/rest/v1/crm_prospect_scans",
                headers=_sb_headers(),
                params={
                    "prospect_id": f"eq.{prospect_id}",
                    "status": "eq.complete",
                    "select": "hawk_score,grade,findings,created_at",
                    "order": "created_at.desc",
                    "limit": "1",
                },
                timeout=20.0,
            )
            sr.raise_for_status()
            rows = sr.json() or []
            scan = rows[0] if rows else None

        company = c.get("company_name") or "Client"
        domain = c.get("domain") or "—"
        html = build_monthly_html(company_name=str(company), domain=str(domain), month_label=month_label, scan=scan)
        pdf = html_to_pdf_bytes(html)
        if not pdf:
            errors.append(f"{cid}: pdf generation failed")
            httpx.post(
                f"{SUPABASE_URL}/rest/v1/crm_monthly_report_log",
                headers=_sb_headers(),
                json={
                    "client_id": cid,
                    "month_year": month_year,
                    "sent_to_email": to_email,
                    "status": "failed",
                },
                timeout=15.0,
            )
            continue

        path = f"monthly/{cid}/{month_year}.pdf"
        if not upload_report_pdf(path, pdf):
            errors.append(f"{cid}: storage upload failed")
            continue

        b64 = base64.b64encode(pdf).decode("ascii")
        try:
            send_monthly_email(to_email=to_email, company_name=str(company), month_label=month_label, pdf_b64=b64)
        except Exception as e:
            logger.exception("resend monthly: %s", e)
            errors.append(f"{cid}: email {e}")
            httpx.post(
                f"{SUPABASE_URL}/rest/v1/crm_monthly_report_log",
                headers=_sb_headers(),
                json={
                    "client_id": cid,
                    "month_year": month_year,
                    "storage_path": path,
                    "sent_to_email": to_email,
                    "status": "failed",
                },
                timeout=15.0,
            )
            continue

        httpx.post(
            f"{SUPABASE_URL}/rest/v1/crm_monthly_report_log",
            headers=_sb_headers(),
            json={
                "client_id": cid,
                "month_year": month_year,
                "storage_path": path,
                "sent_to_email": to_email,
                "status": "sent",
            },
            timeout=15.0,
        )
        sent += 1

    return {
        "ok": True,
        "month_year": month_year,
        "month_label": month_label,
        "sent": sent,
        "skipped": skipped,
        "errors": errors,
    }
