"""Generate HAWK scan report PDF with WeasyPrint."""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from config import BASE_URL
from models import Scan


def _escape(s: str) -> str:
    return (s or "").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;").replace('"', "&quot;")


def build_report_html(scan: Scan, sections: list[str], client_name: str | None = None, client_company: str | None = None) -> str:
    domain = scan.scanned_domain or (scan.domain.domain if getattr(scan, "domain", None) and scan.domain else "unknown")
    score = scan.score or 0
    grade = scan.grade or "—"
    findings: list[dict[str, Any]] = []
    try:
        findings = json.loads(scan.findings_json or "[]")
    except Exception:
        pass

    critical = [f for f in findings if f.get("severity") == "critical"]
    warning = [f for f in findings if f.get("severity") == "warning"]
    info = [f for f in findings if f.get("severity") == "info"]
    ok = [f for f in findings if f.get("severity") == "ok"]

    html_parts = [
        """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<style>
  body { font-family: system-ui, sans-serif; font-size: 12px; line-height: 1.5; color: #1a1a1a; max-width: 800px; margin: 0 auto; padding: 24px; }
  h1 { font-size: 20px; margin-bottom: 8px; }
  h2 { font-size: 16px; margin-top: 24px; margin-bottom: 8px; border-bottom: 1px solid #ddd; }
  .meta { color: #666; margin-bottom: 24px; }
  .grade { font-size: 32px; font-weight: bold; margin: 16px 0; }
  .grade-a { color: #16a34a; }
  .grade-b { color: #2563eb; }
  .grade-c { color: #ca8a04; }
  .grade-d { color: #ea580c; }
  .grade-f { color: #dc2626; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { text-align: left; padding: 8px; border-bottom: 1px solid #eee; }
  th { font-weight: 600; color: #444; }
  .severity-critical { color: #dc2626; }
  .severity-warning { color: #ea580c; }
  .severity-info { color: #2563eb; }
  .severity-ok { color: #16a34a; }
  .footer { margin-top: 32px; font-size: 11px; color: #888; }
</style>
</head>
<body>
""",
        f"<h1>HAWK Security Report</h1>",
    ]
    if client_name or client_company:
        html_parts.append(f'<p class="meta">Prepared for: <strong>{_escape(client_name or "")}</strong>{f" — {_escape(client_company)}" if client_company else ""}</p>')
    html_parts.append(f'<p class="meta">Domain: <strong>{_escape(domain)}</strong></p>')

    if "executive" in sections:
        grade_class = f"grade-{grade.lower()}" if grade and len(grade) == 1 else "grade-f"
        html_parts.append(f'<h2>Executive Summary</h2>')
        html_parts.append(f'<p>Overall grade: <span class="grade {grade_class}">{_escape(grade)}</span> (Score: {score}/100)</p>')
        html_parts.append(f"<p>Critical: {len(critical)} | Warning: {len(warning)} | Info: {len(info)} | OK: {len(ok)}</p>")

    if "findings" in sections and findings:
        html_parts.append("<h2>Findings</h2>")
        html_parts.append("""
<table>
<thead><tr><th>Severity</th><th>Category</th><th>Title</th><th>Remediation</th></tr></thead>
<tbody>
""")
        for f in findings:
            sev = (f.get("severity") or "info").lower()
            html_parts.append(
                f"<tr>"
                f'<td class="severity-{sev}">{_escape(sev)}</td>'
                f"<td>{_escape(str(f.get('category', '')))}</td>"
                f"<td>{_escape(str(f.get('title', '')))}</td>"
                f"<td>{_escape(str(f.get('remediation', ''))[:200])}</td>"
                f"</tr>"
            )
        html_parts.append("</tbody></table>")

    if "compliance" in sections:
        html_parts.append("<h2>Compliance</h2>")
        compliance_refs: set[str] = set()
        for f in findings:
            for c in f.get("compliance") or []:
                compliance_refs.add(c)
        if compliance_refs:
            html_parts.append("<p>This scan surfaces findings relevant to: " + ", ".join(_escape(c) for c in sorted(compliance_refs)) + ".</p>")
        else:
            html_parts.append("<p>No specific compliance references in this scan. See dashboard Compliance page for PIPEDA / Bill C-26 mapping.</p>")

    html_parts.append(f'<p class="footer">Generated by HAWK — {BASE_URL}</p>')
    html_parts.append("</body></html>")
    return "\n".join(html_parts)


def render_report_pdf(scan: Scan, sections: list[str], output_path: Path, client_name: str | None = None, client_company: str | None = None) -> bool:
    """Generate PDF at output_path. Returns True on success."""
    try:
        from weasyprint import HTML
    except ImportError:
        return False
    html = build_report_html(scan, sections, client_name=client_name, client_company=client_company)
    try:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        HTML(string=html).write_pdf(output_path)
        return output_path.exists()
    except Exception:
        return False
