-- Unified Pipeline Rebuild: aria_lead_inventory, aria_domain_health, aria_inbound_replies, crm_settings keys
-- Replaces Charlotte + ARIA pipeline with nightly build + morning dispatch architecture

-- ============================================================================
-- 1. aria_lead_inventory — central lead storage for nightly pipeline
-- ============================================================================

CREATE TYPE aria_lead_email_finder AS ENUM ('prospeo', 'apollo', 'pattern');
CREATE TYPE aria_lead_zb_result AS ENUM ('valid', 'catch_all', 'invalid', 'removed');
CREATE TYPE aria_lead_status AS ENUM (
  'pending',        -- discovered, not yet processed
  'verified',       -- email verified by ZeroBounce
  'scanned',        -- domain scanned by Hawk
  'personalized',   -- email generated by OpenAI
  'ready',          -- fully processed, waiting for dispatch
  'dispatched',     -- loaded into Smartlead campaign
  'suppressed'      -- removed (bounce, unsubscribe, duplicate, etc.)
);

CREATE TABLE IF NOT EXISTS aria_lead_inventory (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Discovery fields (Google Places)
  business_name   text NOT NULL,
  domain          text NOT NULL,
  address         text,
  city            text,
  province        text,
  vertical        text NOT NULL,  -- dental, legal, accounting
  google_rating   numeric(2,1),
  review_count    integer,
  google_place_id text,
  -- Contact fields (Prospeo / Apollo)
  contact_name    text,
  contact_email   text,
  contact_title   text,
  email_finder    aria_lead_email_finder,
  -- Verification
  zero_bounce_result aria_lead_zb_result,
  zero_bounce_data jsonb DEFAULT '{}'::jsonb,
  -- Scan results
  hawk_score      integer,
  vulnerability_found text,
  no_finding      boolean DEFAULT false,
  scan_data       jsonb DEFAULT '{}'::jsonb,
  -- Personalized email
  email_subject   text,
  email_body      text,
  -- Scoring
  lead_score      integer DEFAULT 0,
  -- Dispatch
  status          aria_lead_status DEFAULT 'pending',
  smartlead_campaign_id text,
  scheduled_send_at timestamptz,
  dispatched_at   timestamptz,
  -- Suppression tracking
  suppression_reason text,
  -- Metadata
  nightly_run_date date,
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

-- Indexes for common queries
CREATE INDEX idx_inventory_status ON aria_lead_inventory(status);
CREATE INDEX idx_inventory_vertical_status ON aria_lead_inventory(vertical, status);
CREATE INDEX idx_inventory_domain ON aria_lead_inventory(domain);
CREATE INDEX idx_inventory_email ON aria_lead_inventory(contact_email);
CREATE INDEX idx_inventory_run_date ON aria_lead_inventory(nightly_run_date);
CREATE INDEX idx_inventory_lead_score ON aria_lead_inventory(lead_score DESC);
CREATE UNIQUE INDEX idx_inventory_domain_email_uniq ON aria_lead_inventory(domain, contact_email)
  WHERE contact_email IS NOT NULL;

-- RLS
ALTER TABLE aria_lead_inventory ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all_inventory" ON aria_lead_inventory
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================================
-- 2. aria_domain_health — inbox health monitoring per sending domain
-- ============================================================================

CREATE TABLE IF NOT EXISTS aria_domain_health (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  domain          text NOT NULL,
  -- Metrics (updated by inbox health cron)
  emails_sent_total     integer DEFAULT 0,
  emails_sent_7d        integer DEFAULT 0,
  bounces_7d            integer DEFAULT 0,
  spam_complaints_7d    integer DEFAULT 0,
  replies_7d            integer DEFAULT 0,
  bounce_rate_7d        numeric(5,4) DEFAULT 0,
  spam_rate_7d          numeric(5,4) DEFAULT 0,
  reply_rate_7d         numeric(5,4) DEFAULT 0,
  -- Blacklist monitoring
  blacklisted           boolean DEFAULT false,
  blacklist_entries     jsonb DEFAULT '[]'::jsonb,
  last_blacklist_check  timestamptz,
  -- Status
  health_status   text DEFAULT 'healthy',  -- healthy, warning, paused
  paused_at       timestamptz,
  pause_reason    text,
  -- Metadata
  created_at      timestamptz DEFAULT now(),
  updated_at      timestamptz DEFAULT now()
);

CREATE UNIQUE INDEX idx_domain_health_domain ON aria_domain_health(domain);
CREATE INDEX idx_domain_health_status ON aria_domain_health(health_status);

ALTER TABLE aria_domain_health ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all_domain_health" ON aria_domain_health
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================================
-- 3. aria_inbound_replies — Smartlead webhook reply tracking
-- ============================================================================

CREATE TYPE aria_reply_sentiment AS ENUM (
  'positive',
  'objection',
  'not_interested',
  'unsubscribe',
  'out_of_office',
  'question',
  'other'
);

CREATE TYPE aria_reply_status AS ENUM (
  'pending',        -- awaiting ARIA classification
  'classified',     -- classified, draft ready for review
  'approved',       -- human approved the draft
  'sent',           -- response sent
  'rejected',       -- human rejected the draft
  'auto_handled'    -- auto-handled (OOO, unsubscribe)
);

CREATE TABLE IF NOT EXISTS aria_inbound_replies (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Source
  smartlead_lead_id text,
  smartlead_campaign_id text,
  prospect_email    text NOT NULL,
  prospect_name     text,
  prospect_domain   text,
  -- Reply content
  reply_subject     text,
  reply_body        text NOT NULL,
  reply_received_at timestamptz DEFAULT now(),
  -- ARIA classification
  sentiment         aria_reply_sentiment,
  confidence_score  numeric(3,2),
  classification_reasoning text,
  -- ARIA drafted response
  drafted_response_subject text,
  drafted_response_body text,
  -- Status
  status            aria_reply_status DEFAULT 'pending',
  approved_by       uuid,
  approved_at       timestamptz,
  sent_at           timestamptz,
  -- Link to inventory
  inventory_lead_id uuid REFERENCES aria_lead_inventory(id),
  -- Metadata
  webhook_payload   jsonb DEFAULT '{}'::jsonb,
  created_at        timestamptz DEFAULT now(),
  updated_at        timestamptz DEFAULT now()
);

CREATE INDEX idx_replies_status ON aria_inbound_replies(status);
CREATE INDEX idx_replies_sentiment ON aria_inbound_replies(sentiment);
CREATE INDEX idx_replies_email ON aria_inbound_replies(prospect_email);
CREATE INDEX idx_replies_received ON aria_inbound_replies(reply_received_at DESC);

ALTER TABLE aria_inbound_replies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "service_role_all_replies" ON aria_inbound_replies
  FOR ALL USING (auth.role() = 'service_role');

-- ============================================================================
-- 4. crm_settings — new configuration keys for unified pipeline
-- ============================================================================

INSERT INTO crm_settings (key, value) VALUES
  ('smartlead_campaign_id_dental', ''),
  ('smartlead_campaign_id_legal', ''),
  ('smartlead_campaign_id_accounting', ''),
  ('daily_send_limit', '3000'),
  ('per_inbox_daily_cap', '50'),
  ('pipeline_nightly_enabled', 'true'),
  ('pipeline_dispatch_enabled', 'true'),
  ('google_places_cities', '["Toronto","Vancouver","Calgary","Edmonton","Ottawa","Montreal","Winnipeg","Halifax","Quebec City","Saskatoon","Regina","Victoria","Kelowna","London","Hamilton","Waterloo","Mississauga","Brampton"]')
ON CONFLICT (key) DO NOTHING;
